<?php

namespace MyTravelBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
    public function findByReceiverId($id)
    {
        $dql = "SELECT message FROM MyTravelBundle:Message message WHERE message.receiverId = $id ";
        $travels = $this->getEntityManager()->createQuery($dql)->getResult();
        return $travels;
    }
}
