<?php

namespace MyTravelBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TravelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TravelRepository extends EntityRepository
{
    public function sortById()
    {
        $dql = "SELECT travel FROM MyTravelBundle:Travel travel ORDER BY travel.id DESC ";
        $travels = $this->getEntityManager()->createQuery($dql)->getResult();
        return $travels;
    }
}
