<?php

namespace MyTravelBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TravelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

}