<?php

namespace MyTravelBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TravelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
//    public function findByUsername($id)
//    {
//        $dql = "SELECT fos_user FROM FOSUserBundle:USER user WHERE user.username LIKE";
//        $travels = $this->getEntityManager()->createQuery($dql)->getResult();
//        return $travels;
//    }
}